spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sheikh-qzaman/umayer/blob/master/cloud-config-server/src/main/resources/
server:
  port: 8888