spring:
  application:
    name: url-shortening-service
  redis:
    host: localhost
    port: 6379
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka