spring:
    application:
        name: zuul-api-gateway
server:
    port: 8080
eureka:
    client:
        serviceUrl:
            defaultZone: http://172.31.29.137:8080/eureka
zuul:
    routes:
        shorten:
            serviceId: url-shortening-service 
    host:
        socketTimeoutMillis: 30000