spring:
    application:
        name: zuul-api-gateway
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
zuul:
    routes:
        shorten:
            serviceId: url-shortening-service 
    host:
        socketTimeoutMillis: 30000